apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpclienttests-disabled-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpclienttests-disabled
  template:
    metadata:
      annotations:
        linkerd.io/inject: disabled
      labels:
        app: httpclienttests-disabled
    spec:
      containers:
      - name: httpclienttests-disabled
        resources: {}
        image: httptest.azurecr.io/httpclienttests:$VERSION
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: httpclienttests-disabled-svc
spec:
  type: LoadBalancer
  selector:
    app: httpclienttests-disabled
  ports:
  - port: 80
    targetPort: 80

