apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpclienttests-test-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpclienttests-test
  template:
    metadata:
      annotations:
        linkerd.io/inject: disabled
      labels:
        app: httpclienttests-test
    spec:
      containers:
      - name: httpclienttests-test
        resources: {}
        image: httptest.azurecr.io/httpclienttests:v7
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: test-svc
spec:
  type: LoadBalancer
  selector:
    app: httpclienttests-test
  ports:
  - port: 80
    targetPort: 80

